services:
  # Backend API Service
  - type: web
    name: asset-audit-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: asset-audit-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000

  # Frontend Web Service
  - type: web
    name: asset-audit-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: cd web && npm install && npm run build
    staticPublishPath: web/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: asset-audit-backend
          property: host
        
databases:
  # PostgreSQL Database
  - name: asset-audit-db
    databaseName: asset_audit
    user: asset_audit_user
    region: oregon
    plan: free
